In [1]:
import numpy as np

In [3]:
my_teaser_array = np.array([1,7,19,37,61,91,127,169,217,271,331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])

### np.diff https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.diff.html#numpy.diff

In [4]:
np.diff(my_teaser_array)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [5]:
np.diff(my_teaser_array,n=2)

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [6]:
np.diff(my_teaser_array,n=3)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
from sympy import init_session
init_printing(use_latex='mathjax')

In [21]:
from __future__ import division
from sympy import *
x, y, z, t = symbols('x y z t')
k, m, n = symbols('k m n', integer=True)
f, g, h = symbols('f g h', cls=Function)

In [22]:
diff(x**3)

   2
3⋅x 

In [23]:
diff(x**3,x,2)

6⋅x

In [24]:
diff(x**3,x,3)

6

In [25]:
diff(x**3,x,4)

0

In [26]:
def my_guess(x):
    return (x+1)**3 -(x)**3

In [27]:
my_guess(np.arange(20))

array([   1,    7,   19,   37,   61,   91,  127,  169,  217,  271,  331,
        397,  469,  547,  631,  721,  817,  919, 1027, 1141], dtype=int32)

In [ ]:
#the first row is the teaser_array