# Joining and Splitting arrays
- concatenate
- stack
- split

In [1]:
import numpy as np

### concatenate
documentation: http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [3]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
together.shape

(3, 2)

In [5]:
# we will now evaluate if concatenate  creates copy or view
together[1,1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [6]:
a
#since a remains unchanged, we know that concatenate creates copy 

array([[1, 2],
       [3, 4]])

In [7]:
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [8]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

### stack
## Difference between stack and concatenate is that stack joins the sequence of arrays along a NEW axis (the result has one more axis) while concatenate joins along an EXISTING axis (result has same number of axes).


In [9]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4) # all numbers in the array have mean 3 and std. dev. 4
    
arrays

array([[[-1.13140221,  1.03848199, -1.98584581, -1.97593229],
        [ 2.15362077, -0.29809027, -0.03500702,  0.68361543],
        [-1.83352677,  0.61243533,  0.2688316 , -0.62995836]],

       [[ 0.00628702, -0.18423077, -1.04349705,  0.84990373],
        [-1.59228147, -2.03043196,  0.06482815,  1.77474184],
        [-0.63042778,  0.10509448,  0.18146381,  1.866664  ]],

       [[ 0.82248195,  0.83951576,  0.65723661,  0.1725644 ],
        [ 0.36960297, -0.80892513,  0.88921841,  1.45578956],
        [-0.27371709, -0.91760726,  0.15314121,  1.70789632]],

       [[ 0.14975801,  0.45796235, -1.62838782,  1.10433102],
        [-0.13734078, -0.47600138, -0.9266404 ,  0.30273172],
        [-1.45494555, -0.49969549,  0.52485078,  1.99987088]],

       [[ 0.2374883 , -0.87549309, -0.52329361, -1.79837445],
        [ 0.8444017 , -1.37257443, -0.63250145, -0.38884501],
        [-0.52670512, -1.9458443 ,  2.25474277, -0.36156879]]])

In [10]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [11]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

array([[5, 3, 4],
       [3, 5, 4],
       [3, 4, 5]])

In [12]:
stack0

array([[[-1.13140221,  1.03848199, -1.98584581, -1.97593229],
        [ 2.15362077, -0.29809027, -0.03500702,  0.68361543],
        [-1.83352677,  0.61243533,  0.2688316 , -0.62995836]],

       [[ 0.00628702, -0.18423077, -1.04349705,  0.84990373],
        [-1.59228147, -2.03043196,  0.06482815,  1.77474184],
        [-0.63042778,  0.10509448,  0.18146381,  1.866664  ]],

       [[ 0.82248195,  0.83951576,  0.65723661,  0.1725644 ],
        [ 0.36960297, -0.80892513,  0.88921841,  1.45578956],
        [-0.27371709, -0.91760726,  0.15314121,  1.70789632]],

       [[ 0.14975801,  0.45796235, -1.62838782,  1.10433102],
        [-0.13734078, -0.47600138, -0.9266404 ,  0.30273172],
        [-1.45494555, -0.49969549,  0.52485078,  1.99987088]],

       [[ 0.2374883 , -0.87549309, -0.52329361, -1.79837445],
        [ 0.8444017 , -1.37257443, -0.63250145, -0.38884501],
        [-0.52670512, -1.9458443 ,  2.25474277, -0.36156879]]])

In [13]:
stack1

array([[[-1.13140221,  1.03848199, -1.98584581, -1.97593229],
        [ 0.00628702, -0.18423077, -1.04349705,  0.84990373],
        [ 0.82248195,  0.83951576,  0.65723661,  0.1725644 ],
        [ 0.14975801,  0.45796235, -1.62838782,  1.10433102],
        [ 0.2374883 , -0.87549309, -0.52329361, -1.79837445]],

       [[ 2.15362077, -0.29809027, -0.03500702,  0.68361543],
        [-1.59228147, -2.03043196,  0.06482815,  1.77474184],
        [ 0.36960297, -0.80892513,  0.88921841,  1.45578956],
        [-0.13734078, -0.47600138, -0.9266404 ,  0.30273172],
        [ 0.8444017 , -1.37257443, -0.63250145, -0.38884501]],

       [[-1.83352677,  0.61243533,  0.2688316 , -0.62995836],
        [-0.63042778,  0.10509448,  0.18146381,  1.866664  ],
        [-0.27371709, -0.91760726,  0.15314121,  1.70789632],
        [-1.45494555, -0.49969549,  0.52485078,  1.99987088],
        [-0.52670512, -1.9458443 ,  2.25474277, -0.36156879]]])

In [14]:
stack2

array([[[-1.13140221,  0.00628702,  0.82248195,  0.14975801,
          0.2374883 ],
        [ 1.03848199, -0.18423077,  0.83951576,  0.45796235,
         -0.87549309],
        [-1.98584581, -1.04349705,  0.65723661, -1.62838782,
         -0.52329361],
        [-1.97593229,  0.84990373,  0.1725644 ,  1.10433102,
         -1.79837445]],

       [[ 2.15362077, -1.59228147,  0.36960297, -0.13734078,
          0.8444017 ],
        [-0.29809027, -2.03043196, -0.80892513, -0.47600138,
         -1.37257443],
        [-0.03500702,  0.06482815,  0.88921841, -0.9266404 ,
         -0.63250145],
        [ 0.68361543,  1.77474184,  1.45578956,  0.30273172,
         -0.38884501]],

       [[-1.83352677, -0.63042778, -0.27371709, -1.45494555,
         -0.52670512],
        [ 0.61243533,  0.10509448, -0.91760726, -0.49969549,
         -1.9458443 ],
        [ 0.2688316 ,  0.18146381,  0.15314121,  0.52485078,
          2.25474277],
        [-0.62995836,  1.866664  ,  1.70789632,  1.99987088,
         -0

### split
for information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

In [15]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [16]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [17]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[-1.13140221,  1.03848199, -1.98584581, -1.97593229],
         [ 2.15362077, -0.29809027, -0.03500702,  0.68361543],
         [-1.83352677,  0.61243533,  0.2688316 , -0.62995836]]]),
 array([[[ 0.00628702, -0.18423077, -1.04349705,  0.84990373],
         [-1.59228147, -2.03043196,  0.06482815,  1.77474184],
         [-0.63042778,  0.10509448,  0.18146381,  1.866664  ]]]),
 array([[[ 0.82248195,  0.83951576,  0.65723661,  0.1725644 ],
         [ 0.36960297, -0.80892513,  0.88921841,  1.45578956],
         [-0.27371709, -0.91760726,  0.15314121,  1.70789632]]]),
 array([[[ 0.14975801,  0.45796235, -1.62838782,  1.10433102],
         [-0.13734078, -0.47600138, -0.9266404 ,  0.30273172],
         [-1.45494555, -0.49969549,  0.52485078,  1.99987088]]]),
 array([[[ 0.2374883 , -0.87549309, -0.52329361, -1.79837445],
         [ 0.8444017 , -1.37257443, -0.63250145, -0.38884501],
         [-0.52670512, -1.9458443 ,  2.25474277, -0.36156879]]])]

In [18]:
type(s0)

list

In [19]:
s0[1]

array([[[ 0.00628702, -0.18423077, -1.04349705,  0.84990373],
        [-1.59228147, -2.03043196,  0.06482815,  1.77474184],
        [-0.63042778,  0.10509448,  0.18146381,  1.866664  ]]])

In [20]:
s0[1].shape

(1, 3, 4)

In [21]:
s1=np.split (before_split, 3, axis=1)
s1

[array([[[-1.13140221,  1.03848199, -1.98584581, -1.97593229]],
 
        [[ 0.00628702, -0.18423077, -1.04349705,  0.84990373]],
 
        [[ 0.82248195,  0.83951576,  0.65723661,  0.1725644 ]],
 
        [[ 0.14975801,  0.45796235, -1.62838782,  1.10433102]],
 
        [[ 0.2374883 , -0.87549309, -0.52329361, -1.79837445]]]),
 array([[[ 2.15362077, -0.29809027, -0.03500702,  0.68361543]],
 
        [[-1.59228147, -2.03043196,  0.06482815,  1.77474184]],
 
        [[ 0.36960297, -0.80892513,  0.88921841,  1.45578956]],
 
        [[-0.13734078, -0.47600138, -0.9266404 ,  0.30273172]],
 
        [[ 0.8444017 , -1.37257443, -0.63250145, -0.38884501]]]),
 array([[[-1.83352677,  0.61243533,  0.2688316 , -0.62995836]],
 
        [[-0.63042778,  0.10509448,  0.18146381,  1.866664  ]],
 
        [[-0.27371709, -0.91760726,  0.15314121,  1.70789632]],
 
        [[-1.45494555, -0.49969549,  0.52485078,  1.99987088]],
 
        [[-0.52670512, -1.9458443 ,  2.25474277, -0.36156879]]])]

In [23]:
s2=np.split (before_split, 4, axis=2)
s2

[array([[[-1.13140221],
         [ 2.15362077],
         [-1.83352677]],
 
        [[ 0.00628702],
         [-1.59228147],
         [-0.63042778]],
 
        [[ 0.82248195],
         [ 0.36960297],
         [-0.27371709]],
 
        [[ 0.14975801],
         [-0.13734078],
         [-1.45494555]],
 
        [[ 0.2374883 ],
         [ 0.8444017 ],
         [-0.52670512]]]), array([[[ 1.03848199],
         [-0.29809027],
         [ 0.61243533]],
 
        [[-0.18423077],
         [-2.03043196],
         [ 0.10509448]],
 
        [[ 0.83951576],
         [-0.80892513],
         [-0.91760726]],
 
        [[ 0.45796235],
         [-0.47600138],
         [-0.49969549]],
 
        [[-0.87549309],
         [-1.37257443],
         [-1.9458443 ]]]), array([[[-1.98584581],
         [-0.03500702],
         [ 0.2688316 ]],
 
        [[-1.04349705],
         [ 0.06482815],
         [ 0.18146381]],
 
        [[ 0.65723661],
         [ 0.88921841],
         [ 0.15314121]],
 
        [[-1.62838782],
   

In [38]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [42]:
a.shape
#np.concatenate((a,a[1]),axis=0)

(2, 2)

In [29]:
np.shape([1,2])

(2,)