In [1]:
import numpy as np

In [3]:
# np.matrix is a specialized 2D numpy array that hhas some special properties
my_first_matrix = np.matrix([[3,1,4],[1,5,9],[2,6,5]]) 
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [4]:
#transpose
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [5]:
#inverse
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [7]:
my_first_matrix * my_first_matrix.I
# since the off-diagonal elements are either zero or nearly zero, this must be an Identity matrix

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-16],
        [ 5.55111512e-17, -1.38777878e-16,  1.00000000e+00]])

In [8]:
#create an identity matrix using np.eye(x) x indicates number or rows and cols in identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### solve simultaneous linear equations

In [9]:
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

In [10]:
my_first_inverse = my_first_matrix.I

In [11]:
solution = my_first_inverse * right_hand_side

In [12]:
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [13]:
#AX-B=0
my_first_matrix * solution - right_hand_side

matrix([[ 0.00000000e+00],
        [-3.55271368e-15],
        [ 7.10542736e-15]])

In [14]:
#more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix,right_hand_side)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [15]:
#compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))