In [1]:
import numpy as np

In [15]:
def parseStationFile(filepath):
    parsedFile = {}
    with open(filepath) as fp:
        for index,line in enumerate(fp):
            contents = line.split()
            if('GSN' in line):
                parsedFile[contents[0]]=' '.join(contents[4:])
    return parsedFile

In [16]:
stations = parseStationFile('stations.txt')
def findStation(name, stations):
    return [(key,value) for key,value in stations.items() if name in value]

findStation('LIHUE', stations)



[('USW00022536', 'HI LIHUE WSO AP 1020.1 GSN 91165')]

In [17]:
dly_delimiter = [11,4,2,4]+[5,1,1,1]*31 #we know that the fields are these many characters (ex. ID is 1-11 or 11 chars)
dly_usecols = [1,2,3]+[4*i for i in range(1,32)] #we will be only using YEAR, MONTH and ELEMENT columns
dly_dtype = [np.int32,np.int32,(np.str_,4)] + [np.int32]*31 #here we specify the types of the fields
dly_names = ['year','month','obs'] + [str(day) for day in range(1,31+1)] # here we specify the field names.. obs means observable

def parseFile(filename):
    return np.genfromtxt(
        filename,
        delimiter = dly_delimiter,
        usecols = dly_usecols,
        dtype = dly_dtype,
        names = dly_names
    )

In [20]:
lihue = parseFile('gsn/USW00022536.dly')
lihue[0]

(1950, 2, 'TMAX', 256, 256, 256, 267, 217, 228, 256, 272, 256, 256, 256, 244, 256, 256, 244, 244, 250, 256, 239, 250, 256, 256, 267, 261, 267, 267, 261, 261, -9999, -9999, -9999)

In [56]:
import numpy as np
np.datetime64('{}-{:02}-{:02}'.format(1950,1,1)) 

numpy.datetime64('1950-01-01')

In [1]:
import numpy as np

In [8]:
arrays = [np.random.randn(3) for _ in range(3) ]
arrays

[array([ 0.36039366, -0.84223694,  0.41074539]),
 array([ 0.83935365, -1.1475921 , -1.06774265]),
 array([-1.00299786, -0.93965674,  0.58694002])]

In [9]:
np.stack(arrays, axis=0)

array([[ 0.36039366, -0.84223694,  0.41074539],
       [ 0.83935365, -1.1475921 , -1.06774265],
       [-1.00299786, -0.93965674,  0.58694002]])

In [10]:
np.stack(arrays, axis=1)

array([[ 0.36039366,  0.83935365, -1.00299786],
       [-0.84223694, -1.1475921 , -0.93965674],
       [ 0.41074539, -1.06774265,  0.58694002]])

In [27]:
array = np.array([val for val in np.arange(12)]).reshape(2,2,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [28]:
np.stack(array,axis=0)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
np.stack(array,axis=1)

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])

In [31]:
np.concatenate((array[0],array[1]),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [18]:
arrays[4]

array([[ 0.96494613,  0.56416188,  1.4410658 , -0.52997393],
       [-1.34701826,  0.21712307, -1.17325003, -1.88087616],
       [ 0.80551417, -0.64570833, -0.76901249, -0.02482914]])

In [23]:
print(arrays[0][0])
print(arrays[1][0])
print(arrays[2][0])
print(arrays[3][0])

[-1.4882041  -0.94793056  0.23580173 -3.07607712]
[ 1.66944779  1.34507656 -0.93742681  0.65095821]
[ 0.50085895  0.08814009 -0.23679721  1.16066978]
[-2.24101728 -0.50817285 -0.26033284  0.19396359]


In [21]:
arrays[1][0]

array([ 1.66944779,  1.34507656, -0.93742681,  0.65095821])

In [ ]:
arrays[2]